# Generated by Django 3.1 on 2022-02-13 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0010_auto_20220213_1405'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='variations',
            new_name='variation',
        ),
    ]
